-- Task 1.3: Snowflake foundation
-- Run as ACCOUNTADMIN. Safe to re-run.

USE ROLE ACCOUNTADMIN;

-- Spending limit to protect trial credits
CREATE RESOURCE MONITOR IF NOT EXISTS TRIAL_GUARD
  WITH CREDIT_QUOTA = 20
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

-- Warehouse for loading data from Salesforce
CREATE WAREHOUSE IF NOT EXISTS LOADING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = TRIAL_GUARD
  COMMENT = 'Python extraction loads';

-- Warehouse for dbt transformations (used in Phase 2)
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = TRIAL_GUARD
  COMMENT = 'dbt transformations';

-- Databases and schema
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS RAW COMMENT = 'Raw data exactly as extracted';
CREATE SCHEMA IF NOT EXISTS RAW.SALESFORCE;
CREATE DATABASE IF NOT EXISTS ANALYTICS COMMENT = 'dbt-managed models';