ALTER SESSION SET MULTI_STATEMENT_COUNT = 0;

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS LOADER;
GRANT ROLE LOADER TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE LOADING_WH TO ROLE LOADER;
GRANT USAGE ON DATABASE RAW TO ROLE LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA RAW.SALESFORCE TO ROLE LOADER;

CREATE USER IF NOT EXISTS SVC_LOADER
  TYPE = SERVICE
  DEFAULT_ROLE = LOADER
  DEFAULT_WAREHOUSE = LOADING_WH
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7FAqOab28FY7a0R3WyzFbS3pTI8fy1xTM84TmaKJdPBMwxbLlKE5wXFJj/LgS51vRs+YcGTUskK5TO7YZ7fOxl/vjJ3J7jX9J4S1kXiz4+CXlZkcwTOOkJu4sakoD6HL4xTFIX7eoq9BiIGXzLDkjrmI3maNKxTsvvgqw/O8rHkV2tFpyKcw7JBSW/LWNmFXZ+zl4gWkeN9a91PEDQbiCpK92XX/9rqORjtm3NhyN153bXMyqb3od00BCjivZ6o6WmJ83zYekFFKXg3IP/cl5C6nrG/Vpd5rdqPAwtGNwapW+RgXyfnnuVrwmdyxxyqnf8qKLQ5oOKjNqOqOYjIbsQIDAQAB';

GRANT ROLE LOADER TO USER SVC_LOADER;

SET my_user = CURRENT_USER();
GRANT ROLE LOADER TO USER IDENTIFIER($my_user);

DESC USER SVC_LOADER;